### ISSUE TITLE
Use `__visible_fields`

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#133]
We added the `__visible_fields` GET parameter to the API, but we're not currently using it for Piccolo Admin's list page.

**Comment by sinisaos** [comment]
@dantownsend I know your intention here is to avoid over-fetching api, but this may not work (maybe I'm wrong) because we need all the columns from api to be able to post and edit data in tables.

**Comment by dantownsend** [comment]
@sinisaos Ah, OK - if it's not possible, then it's fine.

It's not a deal breaker, just a nice to have.

**Comment by sinisaos** [comment]
@dantownsend  I think you can close this issue because we already discussed it when we created the `TableConfig` feature [here](https://github.com/piccolo-orm/piccolo_admin/issues/73#issuecomment-928938437) and [here](https://github.com/piccolo-orm/piccolo_admin/issues/73#issuecomment-928988199)
