### ISSUE TITLE
Problem with left sidebar menu on small screens

### ISSUE THREAD

**Issue by sinisaos** [piccolo-orm/piccolo_admin#140]
I didn't realise before, but there is problem with left sidebar menu on small screens after latest loading UI changes.

![sidebar](https://user-images.githubusercontent.com/30960668/147203605-c100b89e-36c4-4788-8084-15fc3ab59221.png)

**Comment by dantownsend** [comment]
@sinisaos Ah, good catch - this was my fault. The sidebar just needs a z-index value adding. Will fix it now.

**Comment by dantownsend** [comment]
@sinisaos I just pushed a new version to Piccolo Admin. Does this fix the issue for you?

**Comment by sinisaos** [comment]
@dantownsend Yes. Issue resolved. Thanks.

**Comment by dantownsend** [comment]
@sinisaos Cool, thanks a lot
