### ISSUE TITLE
Editting a item if primary key is a uuid yields a 400 Bad Request

### ISSUE THREAD

**Issue by cheesycod** [piccolo-orm/piccolo_admin#145]
INFO:     49.207.216.211:0 - "GET /api/tables/reviews/f46aa57c-6254-4e7f-97c8-4e47065439a8/?__readable=true HTTP/1.1" 400 Bad Request

**Comment by cheesycod** [comment]
This also breaks the actual edit

**Comment by sinisaos** [comment]
@cheesycod I can't replicate the issue. Do you have install the latest Piccolo dependencies? If you git clone Piccolo Admin repo, Studio table has `uuid` primary key and relation to Movie table and everything work fine. Can you check that?

**Comment by dantownsend** [comment]
Yeah, as @sinisaos says it's worth updating to the latest Piccolo and Piccolo API. If it's still not working we'll investigate further.

**Comment by dantownsend** [comment]
Can we close this, or is it still an issue?

**Comment by cheesycod** [comment]
no longer an issue

**Comment by dantownsend** [comment]
@cheesycod cool, thanks
