### ISSUE TITLE
Wysiwyg editor

### ISSUE THREAD

**Issue by sinisaos** [piccolo-orm/piccolo_admin#152]
@dantownsend are you perhaps interested in adding wysiwyg editor to textarea fields?

https://user-images.githubusercontent.com/30960668/158114813-3fa9b405-e87e-438e-84a1-5a2395cc145e.mov

**Comment by dantownsend** [comment]
@sinisaos It's a nice idea. The widget fits in well.

I think something like this should be configurable, rather than always on. In ``TableConfig`` there might be a rich text option or something.

```python
TableConfig(Movie, rich_text_columns=[Movie.content])
```

What widget is it?

**Comment by sinisaos** [comment]
@dantownsend It is a [Vue2Editor](https://www.vue2editor.com/) based on [Quill](https://quilljs.com/). This feature is only for textarea fields and I think the boolean value is enough

```python
TableConfig(Movie, rich_text_widget=True) # default value is false and rich_text_widget is optional
```
If you want I can do PR?

**Comment by dantownsend** [comment]
It's more convenient having a boolean, but I can imagine situations where you only want it for a subset of fields.

Imagine you had a blog post table. You might have a column for the description, which is plain text, and a column for the post contents, which is rich text.

What about:

```python
TableConfig(Movie, rich_text_columns=[Movie.content])

# OR, for all:
TableConfig(Movie, rich_text_columns=['__all__'])
```

**Comment by sinisaos** [comment]
@dantownsend Makes sense. I will try to do that.

**Comment by dantownsend** [comment]
@sinisaos Thanks. I think my only concern is it could lock us into Vue 2. I wonder if there are any widgets which work on Vue 2 and Vue 3?

**Comment by sinisaos** [comment]
@dantownsend I don't know when you plan to switch to Vue 3, but I don't think there should be a problem with any rich text editor (I've tried it with CKEditor and it also works) because when we save form data, we actually use data from the hidden textarea field, and not from the widget. Something like this

```javascript
// InputField.vue
<div v-else-if="format == 'text-area' && isFilter == false">
    <vue-editor
        v-model="localValue"
        v-bind:name="getFieldName(title)"
        :editor-toolbar="customToolbar"
    />
    <textarea   //  we use data from this hidden textarea field
        id="editor"
        v-model.lazy="localValue"
        v-bind:name="getFieldName(title)"
    ></textarea>
</div>

<style scoped lang="less">
textarea#editor {
    display: none;
}
</style>
```

**Comment by dantownsend** [comment]
Ideally we would use the WYSIWYG library directly, instead of via a third party Vue wrapper.

Here's an example where someone has written their own Vue component which wraps Quill. It would be good to do something like this if possible:

https://pineco.de/wrapping-quill-editor-in-a-vue-component/

**Comment by sinisaos** [comment]
@dantownsend I can't make this to work. Wrapper does not work on form submit. 

For Vue 3 we have several options ([CKEditor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v3.html) or [vue-quill](https://github.com/vueup/vue-quill)) and we can use the hidden textarea to submit content. Everything will be fine and the transition should not be difficult. 

If you want I can do PR with working code (configurable `TableConfig` and `Vue2editor` widget), then you can modify or close it.

**Comment by dantownsend** [comment]
@sinisaos Yeah, create a PR and I'll take a look. Thanks

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo_admin/pull/153
