### ISSUE TITLE
Add bulk update option

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#158]
If would be great if we had a bulk update option, where you select some rows, then can set a value on all of those rows. For example, with blog posts, setting them all from 'draft=True' to 'draft=False'.

**Comment by sinisaos** [comment]
@dantownsend If you don't mind we can use Javascript `prompt()` to easy achieve this. Very similar to bulk delete. Something like this:
```javascript
// in RowListing.vue
methods: { 
    ...
    async updateRows() {
        let data = {}
        let column = prompt(
            "Enter the name of the column you want to update"
        )
        data[column] = prompt("Enter the value you want to update")
        for (let i = 0; i < this.selectedRows.length; i++) {
            await this.$store.dispatch("updateRow", {
                tableName: this.tableName,
                rowID: this.selectedRows[i],
                data: data
            })
        }
        await this.fetchRows()
    },
    ...
}
```
If you think this idea is acceptable, I can do PR to see all the code.

**Comment by sinisaos** [comment]
@dantownsend What do you think about this?

**Comment by dantownsend** [comment]
Implemented by https://github.com/piccolo-orm/piccolo_admin/pull/166
