### ISSUE TITLE
Reduce (if) unnecessary dependencies

### ISSUE THREAD

**Issue by virajkanwade** [piccolo-orm/piccolo_admin#159]
I am working on blacksheep + uvicorn project.

But when I install piccolo_admin, it installs lot of other things.

``` 
  • Installing sniffio (1.2.0)
  • Installing anyio (3.5.0)
  • Installing hpack (4.0.0)
  • Installing hyperframe (6.0.1)
  • Installing starlette (0.19.1)
  • Installing fastapi (0.77.1)
  • Installing h2 (4.1.0)
  • Installing priority (2.0.0)
  • Installing python-multipart (0.0.5)
  • Installing aiofiles (0.8.0)
  • Installing hypercorn (0.13.2)
  • Installing piccolo-api (0.33.1)
  • Installing piccolo-admin (0.20.0)
```

Not sure about all of them, but my guess is starlette, fastapi, hypercorn are probably not required for blacksheep + uvicorn project.

Can it be made configurable/ optional to keep the footprint small?

**Comment by sinisaos** [comment]
@virajkanwade Piccolo Admin is FastAPI based admin (which is based on Starlette) and under the hood use PiccoloCRUD (Piccolo API feature) for crud on Piccolo tables. I think all this dependencies is necessary for using Piccolo ecosystem in BlackSheep or any other framework which supports mounting Piccolo Admin.

**Comment by dantownsend** [comment]
Yeah @sinisaos is right - most of these are required. The only things which we could potentially make optional are uvicorn and hypercorn, but most projects will needs one of those anyway.

**Comment by virajkanwade** [comment]
Got it.

Thanks

**Comment by virajkanwade** [comment]
Sorry, one more question:
Is it advisable to use piccolo_admin in production environment? Or should it be only used in dev?
