### ISSUE TITLE
Feature request: support choices in array fields

### ISSUE THREAD

**Issue by scott2b** [piccolo-orm/piccolo_admin#161]
From what I can tell, it seems like this has not been implemented yet, unless I am doing something wrong. It would be nice to have choices dropdown support for arrays the way choices work for individual fields.

For example, I have the following array field with choices being set to an Enum, but it appears to have no effect in the admin UI, whereas for non-arrayed Varchar field we would see a dropdown of choices from the ModelChoice Enum as expected.

```
models:list[str] = Array(base_column=Varchar(length=32, choices=ModelChoice))
```

**Comment by dantownsend** [comment]
Interesting - seems like this isn't implemented in the front end.
