### ISSUE TITLE
Database error text not being shown in admin UI

### ISSUE THREAD

**Issue by ethagnawl** [piccolo-orm/piccolo_admin#167]
I'm seeing some (potentially) unexpected behavior when encountering database-level input validation errors.

For example, if I have a table (app_user) whose `name` column has a uniqueness constraint on it, an admin entering a duplicate name is met with a 500 HTTP response whose "Internal Server Error" body is displayed to the user upon submitting the form. This isn't very helpful to a non-technical user.

Is this the expected behavior and the burden is on the implementer to handle the form validation and error messaging or should the error message returned to the UI contain the contents of the database's error message? From looking through endpoints.py, I _think_ it should be the latter (400 response with `{"message": ...}` body) but I'm not certain.

**Comment by sinisaos** [comment]
We can use generic exception to catch database errors on `post_single`, `put_single` and `patch_single` in Piccolo API crud endpoints like this:
```python
except Exception as e:
    return Response(
        f"Unable to save the resource: {e}", status_code=400
    )
```
Result is:
![error](https://user-images.githubusercontent.com/30960668/173509484-5ba19865-00f3-41d8-8b76-c0ca28c41c04.png)

**Comment by dantownsend** [comment]
@sinisaos Thanks, that could work.

Ideally we would be able to just catch certain exceptions, for example unique errors. There's a [PR](https://github.com/piccolo-orm/piccolo/pull/493) open in Piccolo, but I haven't finished it yet. The idea is it will map the asyncpg or aiosqlite exceptions into generic Piccolo exceptions (for example UniqueException). For now though, this might be our best option.

**Comment by sinisaos** [comment]
@dantownsend Like you said that would be ideal because they would have the same error message for different db drivers. Once you finish with Piccolo PR you can mention me in the comments and I can do PR in Piccolo API and Piccolo Admin to implement this feature. Something like this
```python
from piccolo.engine.exceptions import UniqueConstraintError # or different name of exception
...
except UniqueConstraintError as exception:
    return Response(
        f"Unable to save the resource: {exception}", status_code=400
    )
...
```

**Comment by dantownsend** [comment]
@sinisaos Cool, thanks - that looks good.

**Comment by ethagnawl** [comment]
Thanks for the prompt response, @sinisaos and @dantownsend! Any of the above would make for a much better UX.

**Comment by dantownsend** [comment]
Sorry, progress on this stalled. Going with something similar to @sinisaos solution (https://github.com/piccolo-orm/piccolo_api/issues/186). It will now show a proper error message if a unique constraint fails rather than just a 500.

**Comment by dantownsend** [comment]
In Piccolo API 0.47.0 this should be fixed.

I'll create some follow up tasks, as there's still more we can do with error messages in Piccolo Admin.
