### ISSUE TITLE
Move `MediaStorage` / `LocalMediaStorage` / `S3MediaStorage` to `piccolo_api`

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#192]
I would like to integrate our media storage code with `PiccoloCRUD` at some point. So really, the media storage code should live in Piccolo API (otherwise we will have circular dependency between `piccolo_admin` and `piccolo_api`).

So everything in `piccolo_admin/media` should move to `piccolo_api/media`. Likewise, with the associate tests.

The docs can stay as part of Piccolo Admin for now. We just need to update the imports so they're from `piccolo_api.media`.

**Comment by dantownsend** [comment]
@sinisaos What do you think about this?

Just wondering whether to do it before releasing the next version of Piccolo Admin.

**Comment by sinisaos** [comment]
@dantownsend I think it's a good idea because, as you said, we will prevent circular dependency, but as I mentioned before, it would be very nice and useful for the end user, because they would have everything prepared on the backend and only need to make the frontend.

**Comment by sinisaos** [comment]
@dantownsend If you want I can make these changes in Piccolo API and Piccolo Admin? Of course, you'll have to check if I did everything right.

**Comment by dantownsend** [comment]
@sinisaos If you wouldn't mind, that would be great - thanks

**Comment by sinisaos** [comment]
@dantownsend I will do it during the day.

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo_admin/pull/193
