### ISSUE TITLE
Update image or button for media storage

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#194]
I just realised that the screenshot in the media storage docs no longer reflect how the UI actually looks.

<img width="781" alt="Screenshot 2022-08-06 at 20 32 09" src="https://user-images.githubusercontent.com/350976/183263677-901c1fd2-47fd-40a3-9e8b-afed15875f95.png">

The options are: add a new screenshot and / or make the button UI match.

**Comment by sinisaos** [comment]
@dantownsend We can show upload buttons like [this](https://github.com/piccolo-orm/piccolo_admin/pull/189#discussion_r937436404).

**Comment by sinisaos** [comment]
@dantownsend What do you think about this. Does that look good to you?

**Comment by dantownsend** [comment]
The problem with using native input select widgets, is they do look out of place. But I think having a big button could be confusing, as it looks visually too similar to the main save button.

Maybe the button is just underlined text, instead of a solid button.

Maybe we just update the docs for now in a quick PR, and then think about a better design?

**Comment by sinisaos** [comment]
@dantownsend This is done. You can close this issue.
