### ISSUE TITLE
Improve error messages in Piccolo Admin

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#213]
If we get an error response back from the server when saving a row, we show the response in the UI.

This is if we get a validation error from Pydantic:

<img width="702" alt="Screenshot 2022-09-02 at 12 13 43" src="https://user-images.githubusercontent.com/350976/188127742-8d808366-d2b0-4b03-bc4b-739289e5e2e9.png">

This is if we get a database error:

<img width="748" alt="Screenshot 2022-09-02 at 12 14 03" src="https://user-images.githubusercontent.com/350976/188127784-b483b5a7-7095-43dc-b466-71aec736615f.png">

It would be good if we parsed these errors where possible, and created an improved UI.

Related to https://github.com/piccolo-orm/piccolo_admin/issues/167

**Comment by sinisaos** [comment]
@dantownsend Maybe the error messages could look like this?

![db_errors](https://user-images.githubusercontent.com/30960668/188227966-20517961-5bdf-4819-9fec-db14495be77c.png)

and pydantic validation errors like this

![pydantic](https://user-images.githubusercontent.com/30960668/188228571-a4e32ff4-e194-4a58-8482-e6ca292af8c1.png)

**Comment by dantownsend** [comment]
Yes, something like that. I think the only problem is it looks visually very similar to a button.

Maybe red text will work, without a background?

**Comment by sinisaos** [comment]
If we use only the text, then we can display the entire error message so the user knows what the problem is, like this

![pydantic_error](https://user-images.githubusercontent.com/30960668/188259124-2ca378a3-b3a2-4527-9537-e510f124ca2a.png)

or 

![db_error](https://user-images.githubusercontent.com/30960668/188259135-4d1dd376-8736-42db-9fab-285ae1b753de.png)

**Comment by sinisaos** [comment]
Or maybe like this so it looks different from the button.

![error](https://user-images.githubusercontent.com/30960668/188699721-f6d58c0e-514a-4cff-b2ba-479f9827d558.png)

**Comment by dantownsend** [comment]
Yeah, that could work. Do you think we need the close button? It balances the design nicely, but I wonder if someone would want to hide it.

How about adding a warning icon too?

![188699721-f6d58c0e-514a-4cff-b2ba-479f9827d558](https://user-images.githubusercontent.com/350976/188729609-33739dc2-027e-4a98-8378-d21eaeda8c4e.png)

**Comment by sinisaos** [comment]
@dantownsend You are right. I made a PR so you can play with this too. Feel free to make changes.

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo_admin/pull/219
