### ISSUE TITLE
Add proper docs

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#22]
At the moment, all of the docs are in the README.

I think it would benefit from proper docs on readthedocs.org, as the project grows in scope.

For example, the README currently doesn't explain how to create admin users on the command line, or how to set a custom title for the admin.

**Comment by sinisaos** [comment]
@dantownsend That's a great idea. I think that Piccolo Admin is a great app and important part of Piccolo ecosystem, so good documentation will attract users.

**Comment by dantownsend** [comment]
@sinisaos Merged in now - thanks again!
