### ISSUE TITLE
Cypress - restart Python server before each test

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#226]
Our process for running Cypress tests at the moment is:

```
# Launch the Python server
python -m piccolo_admin.example

# Run the Vue App
cd admin_ui
npm run serve

# Run Cypress
npm run cypress:run
```

Ideally, between each test we would restart the Python web server, so we start from a blank slate each time. Otherwise some tests may modify the database which effects later tests.

- [ ] Work out if it's possible
- [ ] If so, implement it

**Comment by sinisaos** [comment]
@dantownsend I played around with this a bit but couldn't find a way to do it. I tried `cy.exec()` (though it's considered an anti-pattern) but it didn't work. In the end, I don't think it matters that much, because when we do tests locally, I don't think it's a problem to start the server when the tests are done, and when the tests are done in GH actions with each commit server is restarted automatically (if I understand correctly) .

**Comment by dantownsend** [comment]
Thanks for giving it a go.

One way it's sometimes done is having a REST API endpoint, and Cypress calls that. So `example.py` might have a `/reset` endpoint, which resets the database.

I've been playing around with Playwright. It's an alternative to Cypress, and tests can be written in Python, which would make things like this easier, as we can directly call other Python code from within our tests:

https://playwright.dev/

We could run a test, and then check the results are correct in the database.

I'm not saying we should switch right now, but it's an option if we run into difficult use cases.

**Comment by sinisaos** [comment]
Playwright looks great and seems to have all the features as Cypress but code can be written in Python which is great.

> One way it's sometimes done is having a REST API endpoint, and Cypress calls that. So `example.py` might have a `/reset` endpoint, which resets the database.

I like that idea although I don't know how to restart server from endpoint.

**Comment by dantownsend** [comment]
I don't think we could restart the server, but the `reset` endpoint would delete the data from the database:

```python
await Movie.delete(force=True)
...
```

And call this again:

https://github.com/piccolo-orm/piccolo_admin/blob/13693161f237025a4f715abd4b4bbeda3bda026b/piccolo_admin/example.py#L350

If I had a time machine, I would probably go back and use Playwright instead of Cypress. I still really like Cypress, but being able to use Python directly in our tests gives us way more options.

**Comment by sinisaos** [comment]
Playwright looks interesting. I'll try to rewrite the Cypress tests (we don't have a lot of tests) and see how it works.

**Comment by dantownsend** [comment]
Yeah, have a play around and see what you think.

**Comment by sinisaos** [comment]
Playwright is great and easy to use. I didn't use tests in parallel (tests run much faster than in Cypress, but if we want to speed things up, parallel tests are [easy to implement](https://playwright.dev/python/docs/test-runners#parallelism-running-multiple-tests-at-once)) or async. Rewriting tests is actually easy thanks to [Playwright codegen](https://playwright.dev/python/docs/codegen#running-codegen). I had to slightly modify each generated test, but it went smoothly. I was able to write fixture for reset the database like this 
```python
import pytest
from piccolo_admin.example import Director
from piccolo_admin.example_data import DIRECTORS
from playwright.sync_api import Playwright, sync_playwright


@pytest.fixture
def reset_database() -> None:
    Director.delete(force=True).run_sync()
    Director.insert(*[Director(**d) for d in DIRECTORS]).run_sync()


def test_login_logout(playwright: Playwright, reset_database) -> None:
```
and use that on every test to start with fresh `director` table (in fact, it may not be needed on every test, only on tests that change data in the database after crud operations). Tests would be used by starting `./scripts/dev-server` in one terminal and in second terminal we can start tests with `./scripts/run-e2e-test.sh`. For GH actions I didn't find anything for Python so I'll leave it up to you. If you want I can make a PR so you can see what it's all about.

**Comment by dantownsend** [comment]
Yeah, I really like Playwright too. I also like Cypress, but being able to write tests in Python is very useful.

What you've done there with the fixture looks good to me.

As for GitHub Actions, I'm hoping it's quite straight forward. We `npm install playwright`, run `example.py`, and then launch the tests using pytest.

**Comment by sinisaos** [comment]
@dantownsend You can close this as we no longer use Cypress.
