### ISSUE TITLE
Add help page to docs

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#240]
We don't currently have a help page in the docs.

Our docs are written with Sphinx and reStructuredText, which is the way all official Python documentation is written.

Time required: 10 mins to 1 hour, depending on experience.

- [ ] Create a [new folder in the docs](https://github.com/piccolo-orm/piccolo_admin/tree/master/docs/source), called 'help' with `index.rst` inside.
- [ ] Look at other `rst` files within the docs to see what formatting we use.
- [ ] Add content within `help/index.rst` along the lines of - `To get support please create an issue, or start a new discussion on GitHub`. Take [this as an example](https://piccolo-orm.readthedocs.io/en/latest/piccolo/help/index.html).
- [ ] Add a link to this page in the [table of contents](https://github.com/piccolo-orm/piccolo_admin/blob/master/docs/source/index.rst#table-of-contents) in the root `index.rst` file.

**Comment by RashiSingh20** [comment]
Please assign this task to me

**Comment by ShrinathPawar** [comment]
Will you please assign this issue to me? I would like to work on it.

**Comment by nazmiasri95** [comment]
I'm pickling up this issue 🙌

**Comment by nazmiasri95** [comment]
Here is the PR: https://github.com/piccolo-orm/piccolo_admin/pull/242

**Comment by dantownsend** [comment]
@nazmiasri95 Great, thanks!
