### ISSUE TITLE
datetime picker doesn't support minute granularity

### ISSUE THREAD

**Issue by trondhindenes** [piccolo-orm/piccolo_admin#270]
I've created a table entry like this: `expiry = Timestamptz(null=True)`

A few things I'm noticing in piccolo-admin
- it's not possible for the datetime to be `None`, piccolo-admin always suggests the current time/date
- the datetime picker uses a 12-hour (pm/am) type clock. It would be nice if that was configurable for "non-US" users

I'd really like it to be possible to disable the datetime picker altogether and have users type in a datetime string instead, with the option of having the field empty (indicating `None`) too.

**Comment by sinisaos** [comment]
> I've created a table entry like this: `expiry = Timestamptz(null=True)`
> 
> A few things I'm noticing in piccolo-admin
> 
> * it's not possible for the datetime to be `None`, piccolo-admin always suggests the current time/date

This could be achieved with `expiry = Timestamptz(default=None, null=True)`
> * the datetime picker uses a 12-hour (pm/am) type clock. It would be nice if that was configurable for "non-US" users
> 
> I'd really like it to be possible to disable the datetime picker altogether and have users type in a datetime string instead, with the option of having the field empty (indicating `None`) too.

Flatpickr has configurable options and we could change config options from
https://github.com/piccolo-orm/piccolo_admin/blob/a90ccf1f784696f3bc94a743ca38976542015b2c/admin_ui/src/components/InputField.vue#L56-L59 to this 
```vue
v-bind:config="{
    altInput: true, //new
    allowInput: true, //new
    time_24hr: true, //new
    enableTime: ['date-time', 'time'].indexOf(format) != -1,
    disableMobile: true,
    noCalendar: format == 'time'
}"
```
These changes would allow the user to enter your input and have a 24-hour format

**Comment by trondhindenes** [comment]
> This could be achieved with expiry = Timestamptz(default=None, null=True)

You are absolutely correct. Thanks!

**Comment by dantownsend** [comment]
Yeah, it's a good point.

Do we just modify Piccolo admin so it support seconds out of the box, or make it configurable via `TableConfig`.

It's where we draw the line too - should microseconds also be allowed?

**Comment by dantownsend** [comment]
Just revisiting this - I'm working on a project at the moment where microseconds are required. Would be nice to have a solution for this.
