### ISSUE TITLE
A simple search/filter box for tables in the sidebar

### ISSUE THREAD

**Issue by sinisaos** [piccolo-orm/piccolo_admin#276]
Can we enable a simple table filter/search in the sidebar, because if we have a lot of tables it's a bit hard to find the table you're looking for? Something like this.

![search](https://user-images.githubusercontent.com/30960668/212179074-66c22780-09ad-4274-a70e-1c4f77875c67.png)

**Comment by dantownsend** [comment]
I guess it depends how many tables you have.

We had a suggestion in the past to be able to group tables, which is one solution.

One thing we could do is have the search / filter if there's more than say 10 tables. What do you think?

**Comment by sinisaos** [comment]
> One thing we could do is have the search / filter if there's more than say 10 tables. What do you think?

I think that would be enough. I can do a PR for that if you want and if it's not good enough you can change it or close it.

**Comment by sinisaos** [comment]
Ok, then I'll leave it up to you. I'm closing this issue.
