### ISSUE TITLE
Page admin is not displayed in https mode, but in http it work well

### ISSUE THREAD

**Issue by Edw125** [piccolo-orm/piccolo_admin#288]
Hello. I want to build service that includes piccolo admin. Basically everything is great, but I installed the certificates SSL on my dev server and I ran into a problem. I have the following components: nginx, fastapi, piccolo orm and admin. When I try to open the site in dev mode with using ssl I get page without static like this 
![image](https://user-images.githubusercontent.com/57034089/218340047-f4be0de2-a253-4cc3-be42-af3ebaf8eff0.png)
in logs I see what subrequests are sent with 404 code
![image](https://user-images.githubusercontent.com/57034089/218340064-a0bcc7e3-447b-427e-b345-36d655c97631.png)
I understood that static files such as html css js are located in folder venv/lib/...., but in docker I didn't find it. Maybe need configure in any way nginx to serve static?

How to solve this? Thanks for answers

**Comment by sinisaos** [comment]
@Edw125 as @dantownsend already wrote [here](https://github.com/piccolo-orm/piccolo/issues/763#issuecomment-1427147486) you should use the `allowed_hosts` argument when serving under `https` and everything should be fine.
