### ISSUE TITLE
Abstraction for generic admin panel use

### ISSUE THREAD

**Issue by eddsalkield** [piccolo-orm/piccolo_admin#29]
Firstly, thanks so much for your amazing work on this project.

I'm looking to build a generic library for admin interface components that tie into CRUD operations within ASGI apps, since one doesn't really exist within the ASGI ecosystem.  Since the `piccolo_admin` Vue app is predominantly built of well-separated components, and relies on a well-defined [API layer](https://piccolo-api.readthedocs.io/en/latest/crud/piccolo_crud.html), it could form a good foundation for this project; alternative CRUD backends could be created that conform to a similar API spec, and therefore make use of the frontend components you've built.

I was considering forking the project to achieve this, but I was wondering if you'd be willing to collaborate with me in abstracting some of the components of the admin panel into a generic library of admin interface components?   The piccolo admin panel would have to be somewhat restructured to make use of the components in the library, but the components themselves would see more broad use as they could be included as a more integrated part of other web apps.

Certain abstractions, like allowing `fetchTableNames` to be either served by an API endpoint or hard-coded, would allow the end developer to decouple the Vue app from the specifics of the API structure as defined [here](https://github.com/piccolo-orm/piccolo_admin/blob/5a6ed1e2a3447c938c4b32ae2c9117b4fe3e1397/piccolo_admin/endpoints.py#L94), and therefore depend only on the CRUD routes.

One advantage of this approach is that both the piccolo project and any parallel projects using the same admin panel library would mutually benefit from updates to the interface components.  More eyeballs on the code might help push this forward to become the prevailing open source admin panel for API-driven web apps.  Indeed, existing ASGI apps could use this library to easily add a custom admin panel without changing their underlying ORM.

It would be interesting to hear your thoughts :smile:

**Comment by dantownsend** [comment]
Hi @eddsalkield - thanks for your interest in the project.

As you mention, the UI is entirely decoupled from the backend. In theory, any server following the same API spec would work with it.

At the moment the UI files are bundled with the Python package, but they could be split into a separate repo, and put onto a CDN instead.

Piccolo Admin uses Session Auth with cookies and CSRF protection. Security wise, I believe this is the best option. However, I can imagine people would want to support other authentication mechanisms like JWT. Somehow the UI would have to support multiple options.

@sinisaos What do you think?

**Comment by sinisaos** [comment]
@dantownsend  I agree that Session Auth with cookies and CSRF protection, from security wise, the best option. If we decouple Vue app and serve from another domain we lose all that benefit. Auth in SPA apps could be pain and propper implementation [add a lot complexity](https://medium.com/lightrail/getting-token-authentication-right-in-a-stateless-single-page-application-57d0c6474e3). In most cases every framework admin UI is tightly coupled with ORM.

@eddsalkield As Daniel says you could separate the Vue application and any server that follows the same API specifications could work with it, but you have to provide all the backend implementation by yourself (security, crud, ratelimiting etc). I think it’s a much easier to use the Piccolo ORM ecosystem because it already offers everything out of the box. You just need to run a few migrations, create an admin user and you are ready to create fully functional applications very quickly and securely. Piccolo already has integration with Starlette and FastAPI, which are the two most popular ASGI frameworks, and you can choose which [one to use](https://piccolo-orm.readthedocs.io/en/latest/piccolo/asgi/index.html). Sorry if I miss your point.

**Comment by sinisaos** [comment]
@eddsalkield All suggestions are welcome if you have any idea for improvements or some new feature that will improve the Piccolo admin. Thanks in advance.

**Comment by eddsalkield** [comment]
Thanks for your responses, and being open to think through my suggestions.

Just to be clear, I'm not suggesting that additional authentication schemes are added - merely that we can separate the concerns of components that deal with authentication from those that implement the `piccoloCRUD` API, by assuming that an appropriate authentication scheme already exists.  The advantage is that of reusability of the admin components in the context of existing applications, and of customisability of behaviour.

Suppose that a web application has been created in which the developer has already defined his own authentication and permission scheme, and simply wants to expose an admin interface for certain tables.  He firstly needs to expose CRUD API endpoints to perform the administrative operations, and then couple that with UI components on the front end.

Since the API specification of `piccoloCRUD` is well defined, he might wish to write a router in the backend that, for a given table within a given ORM, exposes API endpoints equivalent to those found in `piccoloCRUD`, with the hope of then being able to make use of the admin panel components found in `piccolo-admin`.

Since an authentication and permission scheme has already been defined within the backend, the developer now simply requires a library of Vue components that couple with the `piccoloCRUD` API.  However, these components are currently intermingled with the rest of the `piccolo-admin` Vue app, so they're hard to reuse in this capacity.

I'm simply suggesting that the components that deal with the `piccoloCRUD` API endpoints are abstracted into a separate library, so that they can be dropped into existing Vue applications to provide an oven-ready, integrated admin panel.

Instead of forking `piccolo-admin` and duplicating the effort of maintaining the components, I was thinking that it might make sense to abstract this functionality away and rebase `piccolo-admin` onto it.

**Comment by dantownsend** [comment]
I can see the argument for making the UI reusable across different frameworks and languages.

The challenge is doing it in a way which doesn’t consume too much time, as we’re limited on resources.

I think the best approach for now would be for you to try and implement a backend which conforms with the current API, and keeping it as generic as possible, so the data layer is pluggable.

We can then look at refactoring the repos, so maybe the UI lives in a separate repo, and the Piccolo admin backend is built on top of this generic backend.

If you want you can make a pull request into Piccolo Admin, so we can provide assistance. We currently have `create_admin` as the entry point, but perhaps you could try creating something like `create_admin_generic` or something.

I’d also like to publish an official API spec, which would make it easier for people to build compatible backends in different languages. Possibly with a testing tool for checking compatibility.

**Comment by dantownsend** [comment]
@eddsalkield We recently refactored the backend to use FastAPI - so we now have a proper API spec if it's useful to you.

You can login here:
https://demo1.piccolo-orm.com/
Username: piccolo
Password: piccolo123

And see the full API docs:

https://demo1.piccolo-orm.com/api/docs#/

**Comment by sinisaos** [comment]
@dantownsend Can you please close this issue due to inactivity.

**Comment by dantownsend** [comment]
@sinisaos Agreed, we can close it for now. Open to revisiting it sometime in the future.

For now, the custom form functionality allows people to use the admin with any data source they like, so we've made progress on this.
