### ISSUE TITLE
Value is not a valid <type> when having column with null=True, default=None, required=False

### ISSUE THREAD

**Issue by metakot** [piccolo-orm/piccolo_admin#290]
piccolo==0.107.0
piccolo-admin==0.44.0
piccolo-api==0.51.0

So I have this simple table

```python
import piccolo.columns as cl
from piccolo.table import Table

class TestTable(Table):
    number = cl.Integer(
        null=True,
        default=None,
        required=False,
    )
```

When I try to add the record in admin, it yells on me
![image](https://user-images.githubusercontent.com/5718037/222501496-d45abd38-f77d-4712-af1c-689492283846.png)

Happens also with other fields like UUID.
What can we do here?

**Comment by sinisaos** [comment]
@metakot This error occurs because `None` is not a valid `int` type, and the `int` type is used to [store whole numbers](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/column_types.html#integer). If you remove `default=None` or set `default=some valid integer`, everything works. Hope that helps.

**Comment by dantownsend** [comment]
I just looked, and it's sending an string to the backend instead of null:

<img width="273" alt="Screenshot 2023-03-02 at 18 30 04" src="https://user-images.githubusercontent.com/350976/222519564-9e55f99c-7a01-4851-a444-9eb2e050a352.png">

Possible fixes - set the default to `0` for now.

In terms of a proper fix, we could automatically convert an empty string value to `null` for integer columns. If we then gave it a placeholder of NULL, it would work quite nicely.

<img width="645" alt="Screenshot 2023-03-02 at 18 34 13" src="https://user-images.githubusercontent.com/350976/222520367-cc950cc9-fe45-4f02-b48f-c6c4d89070dd.png">

**Comment by metakot** [comment]
> @metakot This error occurs because `None` is not a valid `int` type, and the `int` type is used to [store whole numbers](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/column_types.html#integer). If you remove `default=None` or set `default=some valid integer`, everything works. The same goes for `UUID` as `None` is [not a valid type](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/column_types.html#uuid) for `UUID` column default value. Hope that helps.

Sorry, but no. This is nonsense. I can remember a lot of cases there database table has NULL fields and this is ok. The point here was what the piccolo admin cannot work with NULL fields at all (except for FK fields). Ok, I've checked and it works with datetime fields also. So you insist what we can use nullable datetime fields, but not ints?

Also in django it works =)

**Comment by metakot** [comment]
@dantownsend
> convert an empty string value to null for integer columns

Not only integers, but ALL nullable fields except the varchar. And what to do with nullable varchar -- this is different story. Because empty string and NULL is different values with different meaning.

**Comment by metakot** [comment]
As for nullable datetimes:
![image](https://user-images.githubusercontent.com/5718037/222528140-d56648c4-e0a9-4dc6-a6a1-e34be454eeed.png)
This works!

But if I fill the datetime and then changed my mind, I cannot force the null here, there is no button:
![image](https://user-images.githubusercontent.com/5718037/222528388-05c219b4-bf96-4584-b185-233078367daa.png)

**Comment by dantownsend** [comment]
Yeah, null is an option for some fields but not others.

You're right about Varchar - we'll need a 'null' checkbox for that to distinguish between empty strings.

We need to check all of the nullable fields to see which ones work.

**Comment by sinisaos** [comment]
> Sorry, but no. This is nonsense. I can remember a lot of cases there database table has NULL fields and this is ok. The point here was what the piccolo admin cannot work with NULL fields at all (except for FK fields). Ok, I've checked and it works with datetime fields also. So you insist what we can use nullable datetime fields, but not ints?

@metakot I'm sorry I offended you so much. I just wanted to help and I was wrong. Cheers.

**Comment by dantownsend** [comment]
@sinisaos Nothing to apologise for - you were helping as best you could 👍 

I'll have a look into it. I think integer fields is probably a good place to start.

I don't tend to use many nullable columns in my projects besides foreign keys, but I know it'll bite me soon if any of my projects require it.

**Comment by dantownsend** [comment]
I've added support for nullable number fields. I can't release it though because GitHub Actions is down.

For fields like `varchar`, `text`, `uuid` - try typing in `null`. That should work for now, but needs a better solution.

**Comment by dantownsend** [comment]
I released it manually on my local machine - try `piccolo_admin==0.45.0`.

**Comment by metakot** [comment]
As the time flies by, some fields and widgets in admin have been fixed or rewritten and now work fine, so it is the best to close this  issue already, especially since I reported too many unrelated issues in this one github issue, and that is not the way how it must be done. Thank you, gentlemen.

**Comment by dantownsend** [comment]
Thanks - like you say, most of the column types should be nullable now. There might be some edge cases, but we can solve those in a separate issue.
