### ISSUE TITLE
Allow custom links in the sidebar

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#307]
Discussed in https://github.com/piccolo-orm/piccolo_admin/discussions/306

We can add a new section in the sidebar containing user defined links:

![piccolo_admin_links_prototype](https://github.com/piccolo-orm/piccolo_admin/assets/350976/e89fb3a1-1e02-42fc-8e0f-1e1d6d1ee695)

The API would be pretty simple:

```python
app = create_admin(
    ...,
    sidebar_links=[
        ('Charts', '/custom-endpoint'),
        ('Top Movies', '/#/movie?__order=-box_office'),
        ...
    ]
)
```

It's useful for many reasons:

* In the `Top Movies` example, we're providing a quick way to get to certain pages with filters / sorting pre-applied.
* In the `Charts` example, this is if someone has added a custom page that they want to link to.

Considerations:

* Do we call it `links` or `shortcuts`?

**Comment by Fidel-C** [comment]
I think 'shortcuts' is more descriptive.

**Comment by sinisaos** [comment]
> I suppose that the sidebar links will be visible to only the admin users and not show up at all in the swagger docs?

@Fidel-C Piccolo Admin is protected by session auth and only the authenticated admin user can see the admin interface and admin Swagger docs. 
Want to do PR for this? 
If not, I can make a working prototype.

**Comment by Fidel-C** [comment]
@sinisaos  alright thanks for the answer.

**Comment by sinisaos** [comment]
@Fidel-C No problem. You didn't say anything about whether you will do PR or not? Do you want me to do initial PR?

**Comment by Fidel-C** [comment]
> @Fidel-C No problem. You didn't say anything about whether you will do PR or not? Do you want me to do initial PR?

Sorry about that. I think you should.

**Comment by sinisaos** [comment]
@Fidel-C PR #308, so you can try it if you want.

**Comment by dantownsend** [comment]
@sinisaos Thanks
