### ISSUE TITLE
Small improvements to the login page

### ISSUE THREAD

**Issue by sinisaos** [piccolo-orm/piccolo_admin#309]
Small changes to the login page by making the form stand out a bit and showing/hiding the password.

https://github.com/piccolo-orm/piccolo_admin/assets/30960668/64f4ac7e-dc7f-4efd-a53e-d3ce19ef1bed

**Comment by Fidel-C** [comment]
Nice one.
I deployed a piccolo FastApi project to render.com, using ip 0.0.0.0 and port 10000. I created an admin user from terminal which is connected to a supabase db. But each time I try to login from the admin panel, I get "there's a problem loggin in". I also set `allowed_hosts[]` to my  render.com project url, still doesn't work. What could be wrong?

**Comment by sinisaos** [comment]
> Nice one.

Thanks.

> I deployed a piccolo FastApi project to render.com, using ip 0.0.0.0 and port 10000. I created an admin user from terminal which is connected to a supabase db. But each time I try to login from the admin panel, I get "there's a problem logging in". I also set `allowed_hosts[]` to my render.com project url, still doesn't work. What could be wrong?

I've never used `render.com`, but I see it as an alternative to Heroku (especially after they discontinued the free plans). So you can connect Piccolo to the db, do migrations and create a user? You added `allowed_hosts` to` create_admin` without www or https like this `allowed_hosts=[your-app.render.com]`. What does the server log say about the error? Have you tried FastAPI in debug mode to see what happens? It's hard to say what the problem could be with too little information.
`

**Comment by Fidel-C** [comment]
Thanks a lot for your help @sinisaos . I was able to resolve this issue by changing some things in my .env variables.


But the challenge now is attempting to login from the Vue front-end,  which also hosted separately. It continues to show `404 not found` in the render.com logs. I'll still figure that out hopefully.

**Comment by sinisaos** [comment]
@Fidel-C Glad Piccolo Admin is working now. For a separate frontend Vue application, see the backend CORS settings to enable your backend API URL and axios setup (if you use axios) on frontend. When Heroku has a free plan, I remember serving the bundeled Vue app from the FastAPI static directory and everything was fine, something like this (just an example, I can't remember exactly)
```python
app = FastAPI()

app.mount('/', StaticFiles(directory='path-to-your-dist-folder/dist', html=True))
```
. This is an option if you cannot manage to serve the frontend app from a separate host. Good luck.

**Comment by Fidel-C** [comment]
> @Fidel-C Glad Piccolo Admin is working now. For a separate frontend Vue application, see the backend CORS settings to enable your frontend app URL and axios setup of backend API URL (if you use axios) on frontend. When Heroku has a free plan, I remember serving the bundeled Vue app from the FastAPI static directory and everything was fine, something like this (just an example, I can't remember exactly)
> 
> ```python
> app = FastAPI()
> 
> app.mount('/', StaticFiles(directory='path-to-your-dist-folder/dist', html=True))
> ```
> 
> . This is an option if you cannot manage to serve the frontend app from a separate host. Good luck.

Wow thanks a lot this is really interesting

**Comment by Fidel-C** [comment]
> > @Fidel-C Glad Piccolo Admin is working now. For a separate frontend Vue application, see the backend CORS settings to enable your frontend app URL and axios setup of backend API URL (if you use axios) on frontend. When Heroku has a free plan, I remember serving the bundeled Vue app from the FastAPI static directory and everything was fine, something like this (just an example, I can't remember exactly)
> > ```python
> > app = FastAPI()
> > 
> > app.mount('/', StaticFiles(directory='path-to-your-dist-folder/dist', html=True))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > . This is an option if you cannot manage to serve the frontend app from a separate host. Good luck.
> 
> Wow thanks a lot this is really interesting

The CORS errors I'm getting is because I set this `const api = axios.create({ baseURL: 'https://myurl.com', withCredentials: true })` with api as my axios instance. And this `
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ORIGINS,
    allow_methods=["*"],
  `  allow_headers=["*"],`
    allow_credentials=True,
)
` in FastApi app instance. It is particularly complaining about the ` allow_headers=["*"],` It seems not to like the `["*"]`.

**Comment by Fidel-C** [comment]
And when trying to login to Piccolo admin, and the wrong credentials are entered, the request object is logged to the console. I think that can pose a security risk. By helping a malicious user guess the right credentials just by viewing the request object logged to the console.

**Comment by sinisaos** [comment]
> Wow thanks a lot this is really interesting

I found the project and the actual settings to serve from static FastAPI is like this (with CORS middleware)

```python
from fastapi.middleware.cors import CORSMiddleware
from fastapi.templating import Jinja2Templates
from starlette.staticfiles import StaticFiles

app = FastAPI(
    routes=[
        Mount(
            "/admin/",
            create_admin(
                tables=APP_CONFIG.table_classes,
                # Required when running under HTTPS:
                allowed_hosts=["your-backend-api-url"],
            ),
        ),
        Mount("/static/", StaticFiles(directory="static")),
    ],
)

app.mount("/dist", StaticFiles(directory="dist/"), name="dist")
app.mount("/css", StaticFiles(directory="dist/css"), name="css")
app.mount("/js", StaticFiles(directory="dist/js"), name="js")

templates = Jinja2Templates(directory="dist")

origins = [
    "your-frontend-app-url",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```
in Vue app I set axios like this

```javascript
axios.defaults.withCredentials = true
axios.defaults.baseURL = 'your-backend-api-url'
```
I think those settings should be fine for a frontend application from a separate host as well.

**Comment by Fidel-C** [comment]
The user browser

**Comment by Fidel-C** [comment]
> > And when trying to login to Piccolo admin, and the wrong credentials are entered, the request object is logged to the console. I think that can pose a security risk. By helping a malicious user guess the right credentials just by viewing the request object logged to the console.
> 
> Did you mean request payload in user browser network tab or?



The user browser console...not the network tab.

**Comment by Fidel-C** [comment]
> > Wow thanks a lot this is really interesting
> 
> I found the project and the actual settings to serve from static FastAPI is like this (with CORS middleware)
> 
> ```python
> from fastapi.middleware.cors import CORSMiddleware
> from fastapi.templating import Jinja2Templates
> from starlette.staticfiles import StaticFiles
> 
> app = FastAPI(
>     routes=[
>         Mount(
>             "/admin/",
>             create_admin(
>                 tables=APP_CONFIG.table_classes,
>                 # Required when running under HTTPS:
>                 allowed_hosts=["your-backend-api-url"],
>             ),
>         ),
>         Mount("/static/", StaticFiles(directory="static")),
>     ],
> )
> 
> app.mount("/dist", StaticFiles(directory="dist/"), name="dist")
> app.mount("/css", StaticFiles(directory="dist/css"), name="css")
> app.mount("/js", StaticFiles(directory="dist/js"), name="js")
> 
> templates = Jinja2Templates(directory="dist")
> 
> origins = [
>     "your-frontend-app-url",
> ]
> 
> app.add_middleware(
>     CORSMiddleware,
>     allow_origins=origins,
>     allow_credentials=True,
>     allow_methods=["*"],
>     allow_headers=["*"],
> )
> ```
> 
> in Vue app I set axios like this
> 
> ```js
> axios.defaults.withCredentials = true
> axios.defaults.baseURL = 'your-backend-api-url'
> ```
> 
> I think those settings should be fine for a frontend application from a separate host as well.

This is exactly the settings I have but the error in the console is that `allow_headers=["*"]` should not be set when `allow_credentials=True` is also set.

**Comment by sinisaos** [comment]
> The user browser console...not the network tab.

This log came from [here](https://github.com/piccolo-orm/piccolo_admin/blob/8fdebb55e31cd37cf1c97773c396b7dbe514a63c/admin_ui/src/views/Login.vue#L43), but it doesn't matter if we remove that, request payload will be displayed in the user browser's network tab. You cannot control the user's browser, at least I don't know how.

![console](https://github.com/piccolo-orm/piccolo_admin/assets/30960668/741c71ae-f8d1-4701-af63-be88d4e63203)

**Comment by Fidel-C** [comment]
> I don't know. Can you paste here the exact error from the browser console?

![Screenshot (22)](https://github.com/piccolo-orm/piccolo_admin/assets/61763700/080358fb-f2ec-4c80-9a89-19bbbe193f6a)

**Comment by sinisaos** [comment]
@dantownsend This issue has gone in the wrong direction (troubleshooting), but do you agree with these small changes to the login page? If not, I'll close this issue.

**Comment by dantownsend** [comment]
@sinisaos Thanks. So it looks like there are two changes:

1. Adding the border on the login page.
2. Allowing the user to see what they typed in.

I'm neutral on adding the border. I had a Google around, and some login forms have borders, and others don't. The plus is it groups the elements together. But the downside is it takes up space when the screen is small (like on mobile).

I agree that the current design is quite plain, so maybe there are some things we can do to improve the look. Even something like adding an icon or underline to balance the blue.


![login_page_icon](https://github.com/piccolo-orm/piccolo_admin/assets/350976/78ec24bd-a8c8-4596-868a-05a603da9fdb)

<img width="532" alt="login_page_border" src="https://github.com/piccolo-orm/piccolo_admin/assets/350976/63d903d4-f953-4994-9d50-efdf2f476012">

For point 2, it's a nice usability feature, but it depends how it's done. If it relies on any third party JavaScript libraries, then it's best to avoid, because anything touching passwords is best kept as simple as possible. If a third party library was compromised, the password could be exfiltrated.

**Comment by sinisaos** [comment]
@dantownsend I removed the border and underlined the `site_name`.

> For point 2, it's a nice usability feature, but it depends how it's done. If it relies on any third party JavaScript libraries, then it's best to avoid, because anything touching passwords is best kept as simple as possible. If a third party library was compromised, the password could be exfiltrated.

I didn't use a third party library but a simple show/hide with booleans. Here is a [link to the changed file](https://github.com/sinisaos/piccolo_admin/blob/80daa9730eaf826c424def44d8609dbcbbd9c29b/admin_ui/src/views/Login.vue).

**Comment by sinisaos** [comment]
Completed in #310
