### ISSUE TITLE
Fix filtering of array columns when they have choices

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#367]
There's some weird behaviour when trying to filter using array columns which have choices defined.

https://github.com/piccolo-orm/piccolo_admin/assets/350976/59e0aaae-103e-4eca-95fa-a5061f8988e0

When you click on a choice, it immediately de-selects.

**Comment by sinisaos** [comment]
@dantownsend If I completely remove the `isFilter` argument from [ChoiceSelect in ArrayWidget.vue](https://github.com/piccolo-orm/piccolo_admin/blob/e8139a28041b1d8fe79c868da6318c55fdfe835f/admin_ui/src/components/ArrayWidget.vue#L16), everything works normally in the filter and crud forms. Can you check that?

**Comment by dantownsend** [comment]
@sinisaos You're right - that seems to fix it. Good catch!
