### ISSUE TITLE
AttributeError: type object 'Model' has no attribute '_meta'

### ISSUE THREAD

**Issue by jrujano** [piccolo-orm/piccolo_admin#370]
I am using sqlalchemy, and when mounting the admin it gives me the following error

![Captura de pantalla 2024-03-05 225931](https://github.com/piccolo-orm/piccolo_admin/assets/113458812/4964f8cc-55cd-4ebd-b483-093615af607a)

Below I present my files: 

main.py
![code](https://github.com/piccolo-orm/piccolo_admin/assets/113458812/774870a3-511a-476f-8284-8399a5aaa4db)

base_class.py
![base_class](https://github.com/piccolo-orm/piccolo_admin/assets/113458812/63c54a15-4bd8-40fb-9ce0-95b282f96173)

models.py

![model](https://github.com/piccolo-orm/piccolo_admin/assets/113458812/d30b0dca-fb06-44fc-8554-11cb343c874b)

**Comment by sinisaos** [comment]
@jrujano You cannot use SQLAlchemy with Piccolo Admin. Piccolo Admin is the UI for [Piccolo ORM](https://piccolo-orm.readthedocs.io/en/latest/) tables. For SQLAlchemy you can use [Starlette Admin](https://jowilf.github.io/starlette-admin/) or [SQLAlchemy Admin](https://aminalaee.dev/sqladmin/).

**Comment by dantownsend** [comment]
I'm going to close this, as there are no plans to support SQLAlchemy. Instead, a standalone Docker container is my preferred solution https://github.com/piccolo-orm/piccolo_admin/issues/129
