### ISSUE TITLE
Translation Issue with Bulk Update Button

### ISSUE THREAD

**Issue by jrycw** [piccolo-orm/piccolo_admin#375]
When attempting bulk editing for updates and deletes, it seems that the bulk update button is not being translated properly, unlike the bulk delete button which functions correctly. I've tested switching to other languages, and it appears that this issue is not specific to any particular language.

### English
![eng](https://github.com/piccolo-orm/piccolo_admin/assets/67060418/e5a1f057-fa7a-4d7b-8802-bdeab8fff7b5)

### Traditional Chinese (for instance):
![zh_tw](https://github.com/piccolo-orm/piccolo_admin/assets/67060418/2ff6c2c0-b0b1-41f6-a85c-fcfdd8aa7fb1)

**Comment by sinisaos** [comment]
@jrycw Yes, you're right. That line should be
```javascript
<span>
    {{ $t("Update") }}
    {{ selectedRows.length }} {{ $t("rows") }}
</span>
```

**Comment by dantownsend** [comment]
Thanks for reporting this. I've added a PR with the fix suggested by @sinisaos.
