### ISSUE TITLE
Horizontal Scroll Bar On The Admin UI

### ISSUE THREAD

**Issue by AmazingAkai** [piccolo-orm/piccolo_admin#382]
When a table has too many columns, they overflow and some become hidden. This problem can be solved by adding a horizontal scroll bar when there are too many columns.

**Comment by sinisaos** [comment]
@AmazingAkai Sorry if I don't understand correctly, but there is already a horizontal scrollbar (at the bottom of the table) in [RowListing.vue](https://github.com/piccolo-orm/piccolo_admin/blob/1157c120415b54e509f7720daaa587cd2cc9d450/admin_ui/src/views/RowListing.vue#L817) and that bar is shown if there are many columns in the table.

**Comment by AmazingAkai** [comment]
@sinisaos Oops, I didn't see the code and thought it wasn't there. The scroll bar should be at the bottom of the table, but I didn't notice it at first because it's at the bottom of the page.
