### ISSUE TITLE
Swap dependency `fastapi` to `fastapi-slim`

### ISSUE THREAD

**Issue by metakot** [piccolo-orm/piccolo_admin#392]
So the author of fastapi makes this really unwanted change. See https://github.com/tiangolo/fastapi/pull/11522
Some authors (like [this](https://github.com/developmentseed/titiler/pull/815)) already did the rollback, maybe we too?

**Comment by dantownsend** [comment]
I think for Piccolo Admin, using `fastapi-slim` is sufficient, so makes sense to change it.

**Comment by metakot** [comment]
The horonable sir of FastAPI did the [standard] optional dependencies. Issue resolved :)

**Comment by dantownsend** [comment]
Cool, thanks for the update.
