### ISSUE TITLE
Find a replacement for window.opener.postMessage

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#40]
Chrome recently changed how it treats links like `<a href="/some-link" target="_blank">Click me</a>`.

It now sets `window.opener` as undefined on the window / tab which gets opened.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#browser_compatibility
`window.opener` was used by Piccolo Admin to communicate between tabs, so when clicking on the add or edit links above a foreign key selector, it would open the edit/add page in a new tab, and when saved would tell the parent tab to refresh its list of foreign key options.

<img width="937" alt="Screenshot 2021-03-11 at 22 46 25" src="https://user-images.githubusercontent.com/350976/110865493-9ed22700-82bb-11eb-9d87-a8e9f7c08263.png">

It's currently used [here](https://github.com/piccolo-orm/piccolo_admin/blob/bdf9d2494da14aa466778eab582490408bf8a872/admin_ui/src/components/AddRowForm.vue#L65), and [here](https://github.com/piccolo-orm/piccolo_admin/blob/bdf9d2494da14aa466778eab582490408bf8a872/admin_ui/src/components/EditRowForm.vue#L101).

Possible solutions:

 * Somehow use a different target type for links
 * Open the page in an iframe instead, in a popup modal

**Comment by sinisaos** [comment]
@dantownsend I'm using Chromium and Firefox and can't reproduce this problem, but the fix can be setting `target="_self"` in the `router-link` to open link in the same window (frame) as we have in other edit forms. Sorry if I miss the point.

**Comment by dantownsend** [comment]
@sinisaos The original idea was if you were editing a really long form, and the last field was a foreign key, there needed to be a way to add a new related object without then having to reload the page, as you would lose everything you've entered into the form. 

By using `target="_blank"` it opens it in another window / tab, you edit or create a related object, and when you go back to the original tab, the foreign key selector has the updated related object, without having to reload the page and lose any progress.

But the API the browser tabs use to communicate with each other has been disabled by Chrome if using `target="_blank"`.

It's not the end of the world, and not even a bug. It's just a nice little feature which used to work, and no longer does.

In a single page application it would be nice to be able to handle it all within a single browser tab anyway. Maybe the state of the form could be saved in Vuex, or the edit view is in a popup.

<img width="1291" alt="Screenshot 2021-03-12 at 08 15 43" src="https://user-images.githubusercontent.com/350976/110912675-2051a580-830c-11eb-86dd-9c21a6d70b8b.png">

I just thought I'd document it here in case there's a simple solution I'm not seeing.

**Comment by sinisaos** [comment]
@dantownsend Aha now I understand. Then probably modal is best way to go, but you know what is the best.

**Comment by dantownsend** [comment]
@sinisaos I think a modal is the best long term solution, but I was hoping there would be a simple one line fix, but doesn't seem so :)

**Comment by dantownsend** [comment]
This is less of an issue now, as when adding a new row to a related table, you can just search for the new row using our new foreign key selector UI.
