### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cheesycod** [piccolo-orm/piccolo_admin#50]
The admin panel just gives me a blank page when I try visiting it. No errors in console

**Comment by dantownsend** [comment]
@cheesycod Is this when running it locally?

What status code are you getting back? Is there any HTML, or is the page just blank?

**Comment by cheesycod** [comment]
I managed to fix the issue by using Cloudflare Argo. Seems to be a HTTPS issue

**Comment by cheesycod** [comment]
Also, there is no error, the page was just blank

**Comment by cheesycod** [comment]
This is on a VPS

**Comment by dantownsend** [comment]
One thing to be aware of, is there's an `allowed_hosts` argument for `create_admin`:

```python
create_admin([TableA, TableB], allowed_hosts=['my_site.com'])
```

This is an extra security measure, related to CSRF, which only gets used when served under HTTPS. So adding the `allowed_hosts` argument may also fix your problem.

**Comment by cheesycod** [comment]
No, it wasn’t allowed_hosts. The Vue app wasn’t being served correctly unless it was in Cloudflare Argo for some reason
