### ISSUE TITLE
Using bigint is broken due to json max size

### ISSUE THREAD

**Issue by cheesycod** [piccolo-orm/piccolo_admin#55]
Using bigint on large bigints like discord snowflakes (like 818294562677588009) causes it to be rounded/corrupted during transfer due to json max size limits.

For bigint, use string and manually parse the integer maybe?

**Comment by dantownsend** [comment]
Hmm, good catch.

I've been able to replicate the issue, but need to work out how to serialise `BigInt` as a string using Pydantic.

How about using a `Varchar` column instead for storing these values?

**Comment by dantownsend** [comment]
On further investigation, it might be possible to configure Axios to use something like this:

https://github.com/sidorares/json-bigint

**Comment by dantownsend** [comment]
Should be fixed now - https://pypi.org/project/piccolo-admin/0.12.1/

**Comment by cheesycod** [comment]
Cool

**Comment by cheesycod** [comment]
> Hmm, good catch.
> 
> I've been able to replicate the issue, but need to work out how to serialise `BigInt` as a string using Pydantic.
> 
> How about using a `Varchar` column instead for storing these values?

I would love to do this but this is a legacy codebase which:

1) Doesn’t have checks for it to be a integer and instead relies on the database to ensure it’s a actual integer as well as on asyncpg to return a integer

2) Would be hard to fix and need extra checks and triggers for database consistency  that were once done by just having it be a bigint

3) Could be better spent time in making new features that are requested heavily
