### ISSUE TITLE
Null byte string error!

### ISSUE THREAD

**Issue by Anonymous1313-tech** [piccolo-orm/piccolo_admin#66]
I got null byte string error when tried to run piccolo_admin! The problem was in _init_ file! There was string with null bytes! Also version.py was empty! 
I downloaded it from pypi!

**Comment by dantownsend** [comment]
@Anonymous1313-tech Very strange. What system are you on?

I'll investigate.

**Comment by Anonymous1313-tech** [comment]
> @Anonymous1313-tech Very strange. What system are you on?
> 
> I'll investigate.

Windows

**Comment by dantownsend** [comment]
I tried it locally, and it seems to work OK for me.

There were some issues with PyPI earlier on - not sure if when you installed it, it was somehow corrupted?

Can you try reinstalling it? I'll also try installing it on Windows.

**Comment by dantownsend** [comment]
I tried it on Windows 10, using the following steps:

 * Installed Python from the Windows store
 * Opened PowerShell
 * Created virtual env using `python -m venv piccolo_admin_test`
 * `cd piccolo_admin_test`
 * `.\Scripts\activate`
 * `pip install piccolo_admin` (the latest version from PyPI - 0.13.2)
 * `admin_demo`

Seemed to work OK, but I'm no expert on Windows, so there could still be an issue.

**Comment by Anonymous1313-tech** [comment]
> I tried it on Windows 10, using the following steps:
> 
> * Installed Python from the Windows store
> * Opened PowerShell
> * Created virtual env using `python -m venv piccolo_admin_test`
> * `cd piccolo_admin_test`
> * `.\Scripts\activate`
> * `pip install piccolo_admin` (the latest version from PyPI - 0.13.2)
> * `admin_demo`
> 
> Seemed to work OK, but I'm no expert on Windows, so there could still be an issue.

It works fine! Tnx!
