### ISSUE TITLE
Increase test coverage for `create_admin`

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#69]
Just a reminder to myself to increase code coverage for `create_admin`.

**Comment by sinisaos** [comment]
@dantownsend I have a question. If we omit files which only usage is to serve demo app for admin in` pyproject.toml` like this
```
[tool.coverage.run]
omit = ["piccolo_admin/example.py", 
        "piccolo_admin/example_data.py",
        "piccolo_admin/sandbox.py"] 
```
 we can easily achieve coverage over 90. Is this ok or we need to test all files?

**Comment by dantownsend** [comment]
@sinisaos You're right, those files aren't particularly important, and can be omitted from code coverage.

The tests in general for Piccolo Admin are very light, considering how much it does. A lot of it is covered in Piccolo API, but there are some methods in `AdminRouter` which are custom to Piccolo Admin, and I don't think have any coverage:

 * get_root
 * get_user
 * get_meta
 * get_table_list
 * get_site_name

It would be nice to have simple tests for these.

**Comment by sinisaos** [comment]
@dantownsend  `get_root` and `get_meta` are not problem because is not protected by authentication. Something like this.
```python
def test_get_meta(self):
    client = TestClient(APP)

    response = client.get("/meta/")
    self.assertEqual(
        response.json(),
        {"piccolo_admin_version": "0.14.0", "site_name": "Piccolo Admin"},
    )
    self.assertEqual(response.status_code, 200)

def test_get_root(self):
    client = TestClient(APP)

    response = client.get("/")
    self.assertEqual(response.status_code, 200)
```

We even don't need this function `get_site_name` because we can get site_name from `get_meta`.

But, the `get_user` and `get_table_list` functions are protected by authentication and testing with client.post() doesn't work because the CSRF token is missing. The best I can do is check the auth failed.
```python
def test_get_tables_list(self):
    client = TestClient(APP)

    response = client.get("/api/tables/")
    self.assertEqual(response.json(), {"error": "Auth failed"})
    self.assertEqual(response.status_code, 401)
```

**Comment by sinisaos** [comment]
@dantownsend I think you can close this issue because it’s done.
