### ISSUE TITLE
Better UI for JSON fields

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#70]
JSON fields are just treated as strings in the UI.

It would be nice if the UI had an option to show a nicely rendered view of the JSON.

**Comment by sinisaos** [comment]
@dantownsend Did you think about simple solution or?

Simple solution may be something like this

```Vue
// in RowListing.vue
<span v-else-if="row[name][0].match(/{/)">
    <pre>{{ row[name] | prettierJSON }}</pre>
</span>
...
filters: {
    prettierJSON(value) {
        return JSON.stringify(JSON.parse(value), null, 2)
    },
},
```
![FireShot Capture 036 - Piccolo Admin - piccolo_admin](https://user-images.githubusercontent.com/30960668/134118076-c14b6218-1f41-4d0f-8ce6-917ae42e5ba6.png)

**Comment by dantownsend** [comment]
@sinisaos  I think what you've done looks nice.

I'm a bit nervous about matching on a regex though.

It might be better to modify the Pydantic schema so it has a format attribute of 'json' or something like that. Similar to this:

https://github.com/piccolo-orm/piccolo/blob/0f28e07233ea3aa490bbeb0c1b30ada08e4fb2b8/piccolo/utils/pydantic.py#L173-L174

<img width="349" alt="134141281-26da6cd2-4ee2-49aa-9a6a-0050f0e784d0" src="https://user-images.githubusercontent.com/350976/134142562-9c4a090d-d8a8-44ed-96b5-bb6b7f70d623.png">

**Comment by dantownsend** [comment]
@sinisaos Exactly, yeah.

I think the change should go into the main Piccolo repo.

At some point we need to modify Piccolo API, so it just proxies to the code in the main Piccolo repo.

**Comment by dantownsend** [comment]
@sinisaos What do you think of using something like this on the table detail page for editing the JSON?

https://github.com/josdejong/jsoneditor

**Comment by sinisaos** [comment]
@dantownsend Looks nice. I'll try it tomorrow how it works with editing view.

**Comment by dantownsend** [comment]
@sinisaos Cool - it might not be a good option, but worth a try.

**Comment by sinisaos** [comment]
@dantownsend Sorry for the late reply. With all the editors I tried, I couldn't save the editing changes because I couldn't set them as an `input` or `textarea`. My solution is simpler without using an external library. Something like this

```Vue
<div v-else-if="format == 'json'">
    <textarea
        :value="JSON.stringify(JSON.parse(value), null, 2)"
        autocomplete="off"
        ref="textarea"
        v-bind:name="getFieldName(title)"
        v-bind:style="{ height: textareaHeight }"
        v-on:input="setTextareaHeight"
    />
</div>
```
and result is

![FireShot Capture 037 - Piccolo Admin - piccolo_admin](https://user-images.githubusercontent.com/30960668/134620381-672131c0-6437-408b-8683-d2b25a423881.png)

Is this OK?

**Comment by dantownsend** [comment]
@sinisaos Yeah, that sounds like a better solution. The libraries were probably overkill.

**Comment by sinisaos** [comment]
@dantownsend When I am able, I will push commit and include this code. 

I will also include a fix for the color of the banner based on the success or error from #96 or this must go in another PR?

**Comment by dantownsend** [comment]
@sinisaos I think it's me imagining things - I thought the colour of the banner changed if it was an error, but it looks like this code doesn't exist in master.

Should just be a simple modification to this file:

https://github.com/piccolo-orm/piccolo_admin/blob/master/admin_ui/src/components/MessagePopup.vue

Ideally do it as a separate PR, but it's fine either way.

I'll sort out that issue where you can't specify a coroutine as the endpoint.

**Comment by sinisaos** [comment]
@dantownsend I'm already changed that file and i'll make new PR for #96 issue. Cheers

**Comment by sinisaos** [comment]
@dantownsend Can you please close this issue because it's done.
