### ISSUE TITLE
Implement custom forms

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#74]
One of the main strengths of Piccolo admin is it's ability to turn a Pydantic model into a form in the UI. Currently, these Pydantic models are generated from Piccolo `Table` subclasses.

It would be amazing if a custom Pydantic model can be passed to `create_admin`, and it's rendered as a form in the UI. For example:

```python
@dataclasses.dataclass
class FormConfig:
    name: str
    pydantic_model: Type[BaseModel]
    endpoint: Callable


def send_email_endpoint(request, data):
    send_email(data.email, data.title, data.content)
    return 'Success'


class SendEmailModel(BaseModel):
    email: str
    title: str
    content: str


app = create_admin(
    tables=[Director, Movie],
    forms=[
        FormConfig(
            name="Send email",
            pydantic_model=SendEmailModel,
            endpoint=send_email_endpoint
        )
    ]
)
```

A new section would then be rendered in the sidebar.

<img width="345" alt="piccolo_admin_forms_sidebar" src="https://user-images.githubusercontent.com/350976/126406260-803b3632-e31d-4024-a97d-5c3ad5a20c8b.png">

Clicking on one of the forms in the sidebar would open a page containing the form.

When the form is submitted, it would call the specified endpoint.

Adding this to Piccolo admin would massively improve it's utility - some business apps could be built with it, without having to write a single line of front end code.

**Comment by sinisaos** [comment]
@dantownsend I’ve been playing with this for a few days and I also think it would be a really nice feature. I can display forms with `FormConfig` very much like we do with a `Table` subclasses. 

![navbar](https://user-images.githubusercontent.com/30960668/132851258-c1e09225-b004-494e-9e19-725d0c50553f.png)

![emailform](https://user-images.githubusercontent.com/30960668/132851285-7f5ad0c5-1948-4af7-ae04-67db4bea5ed2.png)

![example](https://user-images.githubusercontent.com/30960668/132851303-85dc8122-50f4-43c9-9942-0831748312f5.png)

But the biggest problem is that I can only process one of these forms with a predefined Pydantic model. Here is example of email sent to Local SMTP Server.

![send](https://user-images.githubusercontent.com/30960668/132851782-7a4fcd6e-d595-4c83-9f6e-810b475584ad.png)

How to call the specified endpoint from the frontend code. When the form is submit, we get the form field as json and don't save the data in the database but send `axios.post` with json data to a specific endpoint.
It's OK for one form, but how to dynamically change endpoints for multiple forms without adding methods to source code which end user can't do. I don’t know if you understand what I mean but I can do PR that you can see the code. What are you think about that?

**Comment by dantownsend** [comment]
I'm very excited about this feature.

I was imagining that Piccolo admin would auto generate an endpoint for each form. For example `/api/forms/email` (in a similar way to how we have `/api/table/some_table` for tables). The user would then supply a function for each endpoint which handles the form data.

Originally I thought the user's function could be a FastAPI endpoint, but I think we should abstract it more - so the function is something like:

```python
def my_handler(data):
    if data.foo == 'good':
        return 'All worked OK'
    else:
        raise ValueError("Problem with the foo data supplied")
```

That way the user's code isn't tied to FastAPI at all.

If the handler raises a `ValueError` then we would return a 400 to the user, an error message.

If the function returns some text, we show that to the user.

I'm not sure if that helps at all ...

**Comment by sinisaos** [comment]
@dantownsend That would be really nice, but how to do that. When the form is submitted data is json, and axios is most commonly used library for ajax and `axios` required path to the endpoint (url) to send json to the backend. This is an example of `endpoints.py` for get list of forms names, the form schema, and for post data.
```python
# endpoints.py
import smtplib
from dataclasses import dataclass

# rest of unchanged code

@dataclass
class FormConfig:
    name: str
    pydantic_model: t.Type[BaseModel]
    endpoint: t.Callable

# rest of unchanged code

class AdminRouter(FastAPI):
    # rest of unchanged code
    def __init__(
        # rest of unchanged code
        forms: t.Optional[t.List] = None,
        # rest of unchanged code

        self.forms = forms

        # rest of unchanged code

        api_app.add_api_route(
            path="/forms/",
            endpoint=self.get_forms,  # type: ignore
            methods=["GET"],
            tags=["Forms"],
            response_model=t.List[str],
        )

        api_app.add_api_route(
            path="/forms/{name:str}/schema/",
            endpoint=self.get_single_form_schema,  # type: ignore
            methods=["GET"],
            tags=["Form"],
        )

        # we can add this endpoint to dynamically change endpoints for axios.post
        # api_app.add_api_route(
        #     path="/forms/{name:str}/endpoint/",
        #     endpoint=self.get_single_form_endpoint,  # type: ignore
        #     methods=["GET"],
        #     tags=["Form"],
        # )

        api_app.add_api_route(
            path="/forms/{name:str}/",
            endpoint=self.post_single_form,  # type: ignore
            methods=["POST"],
            tags=["Form"],
        )
    # rest of unchanged code

    ###########################################################################

    def get_forms(self, request: Request) -> t.List[str]:
        return [form.name for form in self.forms]

    def get_single_form_schema(self, request: Request, name: str) -> BaseModel:
        param = request.path_params["name"]
        for form in self.forms:
            if form.name == param:
                return form.pydantic_model.schema()

    # we can add this method to dynamically change endpoints for axios.post
    # but how to attach to the user defined function
    # def get_single_form_endpoint(self, request: Request, name: str) -> str:
    #     param = request.path_params["name"]
    #     for form in self.forms:
    #         print(getattr(form.endpoint, "__name__", repr(form.endpoint)))
    #         if form.name == param:
    #             return getattr(form.endpoint, "__name__", repr(form.endpoint))

    # manually processing the email form but no another form and this is biggest
    # problem because this function is added manually
    async def post_single_form(self, request: Request) -> JSONResponse:
        form = await request.json()

        sender = "from@fromdomain.com"
        receivers = [form["email"]]

        message = f"""From: From Person <from@fromdomain.com>
        To: To Person <{form["email"]}>
        Subject: {form["title"]}

        {form["content"]}
        """

        try:
            smtpObj = smtplib.SMTP("localhost:1025")
            smtpObj.sendmail(sender, receivers, message)
            print("Successfully sent email")
        except smtplib.SMTPException:
            print("Error: unable to send email")

        return JSONResponse({"form": form})

###########################################################################

def create_admin(
    # rest of unchanged code
    forms: t.Optional[t.List] = None,
    # rest of unchanged code
):
    # rest of unchanged code
    return ExceptionMiddleware(
        CSRFMiddleware(
            AdminRouter(
                # rest of unchanged code
                forms=forms,
                # rest of unchanged code
        )
    )

```
Sorry for these long comments, but that makes it easier for me to say what I mean

**Comment by dantownsend** [comment]
No worries! I think we would need an endpoint something like we have for schema, which lists all of the available endpoints.

For example:

```
GET /api/forms

['email']
```

```
GET /api/forms/email

# This is the Pydantic model
{
    'message': 'string'
}
```

To send data back:

```
POST /api/forms/email
```

**Comment by sinisaos** [comment]
Tomorrow I will do a PR with a working example (which we can delete) for one form so you can look at the code.

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo_admin/pull/92
