### ISSUE TITLE
Make sure Piccolo admin works with custom primary key columns

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#81]
When using custom primary key columns, for example:

```python
class MyTable(Table):
    pk = UUID(primary_key=True)
```

There are likely to be some edge cases not currently supported by Piccolo admin.

**Comment by abelayalew** [comment]
Am having issue custom primary key in the admin page with page not found error

**Comment by abelayalew** [comment]
okay thanks, hope it will be fixed soon, am so exited to try everything, its amazing project!!

**Comment by dantownsend** [comment]
@abelayalew Thanks

**Comment by cheesycod** [comment]
has this issue been fixed yet?

**Comment by dantownsend** [comment]
@cheesycod Not yet unfortunately - we'll prioritise it.

**Comment by sinisaos** [comment]
@dantownsend I played around with it a bit and it’s not an easy task. If I understood correctly, `PiccoloCRUD` and `FastAPIWrapper` need to be changed to accept `row_id` as a `int` (like is now) or `string` (UUID), but the whole concept of `crud` operations and `relations` between tables is based on a `Serial` type (`Integer`)?

**Comment by dantownsend** [comment]
@sinisaos Yeah, you're right - the endpoints might need modifying to accept string or integers. I'll take a look to see how feasible it is.

**Comment by sinisaos** [comment]
@dantownsend I managed to do a `crud` either with an `int` or with a `string`, but not both at the same time. I tried typing the `row_id` with `Any` or `Union[int, str]`, but niether worked. I didn't try FK relations.

**Comment by dantownsend** [comment]
This should be fixed now if you upgrade to the latest `piccolo_api` version (0.32.3).

Apologies for the delay on this. I'll close this issue for now - if anyone encounters issues with the fix, feel free to leave more comments on this issue.

**Comment by sinisaos** [comment]
@dantownsend This unfortunately doesn't work. Probably everything is fine with the newest changes in `Piccolo API`, but we will have to change the `Piccolo Admin` as well. I haven't researched too much, but the first problem is that we use the `id` column in `RowListing.vue` 
https://github.com/piccolo-orm/piccolo_admin/blob/70220411ce7bf5d785bbe02d5ffec8f4207be4f0/admin_ui/src/views/RowListing.vue#L99
This piece of code is an example that applies to every line where we use `name == 'id'` or `row.id` and if the user names the column differently, e.g. `pk` nothing will work.  

So first we need to see how to recognize the column name specified by the user. The simplest solution would be to put warning
in Piccolo ORM docs https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/column_types.html#uuidthat  that `UUID` column must be called `id`, but it is not convinient. 
FK relations also doesn't work (edit FK and matching FK). Probably there is some more errors.

**Comment by dantownsend** [comment]
@sinisaos Yeah, I was testing the use case where the primary key is still called `id`. Something like:

```python
class MyTable(Table):
    id = UUID(primary_key=True)
```
You're right, to support primary keys with custom names, we will have to do more work.

The first step is modifying the Pydantic schema so we know the name of the primary key column.

**Comment by dantownsend** [comment]
With the latest versions of Piccolo / Piccolo API / Piccolo Admin, primary keys with custom names are now supported:

```python
class MyTable(Table):
    pk = UUID(primary_key=True)
```

@sinisaos When you've tested it, if it all seems OK I'll close the issue.

**Comment by sinisaos** [comment]
@dantownsend Everything works fine. You can close this issue.

**Comment by dantownsend** [comment]
@sinisaos Great, thanks for your help with this.
