### ISSUE TITLE
Upgrade to Vue 3

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#87]
Vue 2 should still be fine for some time, but Vue 3 is definitely a step up. A first step is working out how much work is involved.

**Comment by sinisaos** [comment]
@dantownsend I started playing with this. There are a lot of changes, but with [this help](https://v3.vuejs.org/guide/migration/migration-build.html#overview) I managed to log in and logged out to admin, but for now the row listing doesn't work. I think the biggest problem will be with libraries compatibility (e.g. `vue-json-excel` for CSV export doesn't work with Vue3 and I don't see much activity in their repository). If you want I can do PR so we can track changes and progress.

**Comment by dantownsend** [comment]
@sinisaos If you could create a PR that would be amazing. The upgrade definitely isn't painless, but the Typescript improvements are worthwhile.

**Comment by sinisaos** [comment]
@dantownsend Great. I will do PR that you can see changes in code.

**Comment by dantownsend** [comment]
Completed in Piccolo Admin v1
