### ISSUE TITLE
Add custom widget for Interval fields

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#9]
Any `Interval` fields are shown as text boxes, where you input a number of seconds. It works fine, but could be more user friendly.

The schema for a table with an Interval column looks like this (accessible via `/api/tables/my_table/schema`).

```json
{
    "title": "MyTableIn",
    "type": "object",
    "properties": {
        "interval": {
            "title": "Interval",
            "extra": {},
            "nullable": false,
            "type": "number",
            "format": "time-delta"
        }
    }
}
```
We can tell if it's an `Interval` from the format field in the schema, which is `"time-delta"`.

**Comment by sinisaos** [comment]
Hi Daniel
How about range slider for `Interval` field. Something like this

![create](https://user-images.githubusercontent.com/30960668/103455892-4eee4700-4cf1-11eb-8ec9-97e07532d3c7.png)

![edit](https://user-images.githubusercontent.com/30960668/103455893-53b2fb00-4cf1-11eb-841b-1cbf2e01b7d4.png)

Which time range and which step would be satisfactory? I put 30 days and step is 15 seconds. If you like this idea I can make PR.

**Comment by dantownsend** [comment]
@sinisaos Yeah, it's tricky with sliders - trying to get the perfect increment is hard. I think there are valid use cases where someone would want to specify `5 seconds`, and others where someone might want `1 year`.

When it's just a number, I think the best solution is to have a slider, and a free text field. Here's an [example](https://simpleinvestmentguide.com/tools/interest-calculator/).

But a free text field with something like `1 hour 42 minutes 30 seconds` in it, would be quite challenging to parse.

One solution would be to have several dropdowns - one each for days, hours, minutes, and seconds.

I think having the dropdowns would be my ideal solution, but the slider is still much better than what we have now.

What do you think?

**Comment by sinisaos** [comment]
@dantownsend I agree with you that sliders it's tricky with range and steps (if range is big and steps are small it's to many steps and slider is to sensitive). Dropdowns will be better but also tricky to make. Maybe something like this https://www.jqueryscript.net/time-clock/duration-days-hours-minutes.html . I
For my example of sliders I used `convertTimeSlider` to convert seconds to human readable output and then put in Vue computed property in `InputField.vue`

```
export const convertTimeSlider = {
    convertTimeSlider: function (timeRange: number) {
        const days = Math.floor(timeRange / (3600 * 24))
        const hours = Math.floor((timeRange % (3600 * 24)) / 3600)
        const minutes = Math.floor((timeRange % 3600) / 60)
        const seconds = Math.floor(timeRange % 60)

        const daysDisplay =
            days > 0 ? days + (days == 1 ? " day " : " days, ") : ""
        const hoursDisplay =
            hours > 0
                ? hours + (hours == 1 ? " hour " : " hours ")
                : ""
        const minutesDisplay =
            minutes > 0
                ? minutes + (minutes == 1 ? " minute " : " minutes ")
                : ""
        const secondsDisplay =
            seconds > 0
                ? seconds + (seconds == 1 ? " second" : " seconds")
                : ""
        return (
            daysDisplay + hoursDisplay + minutesDisplay + secondsDisplay
        )
    }
};
```

**Comment by sinisaos** [comment]
@dantownsend And btw interest calculator look awesome.

**Comment by dantownsend** [comment]
@sinisaos Thanks, I'm pleased with the interest calculator. It was an unusual thing to spend my spare time on, but was educational!

Here's a simple example of what a dropdown based widget would look like:

```vue
<template>
    <div class="timestamp_widget">
        <div class="segment">
            <p>Weeks</p>
            <select v-model.number="weeks" v-on:change="emitEvent" placeholder="Weeks">
                <option v-for="week in weekRange" :key="'w' + week">
                    {{ week }}
                </option>
            </select>
        </div>

        <div class="segment">
            <p>Days</p>
            <select v-model.number="days" v-on:change="emitEvent">
                <option v-for="day in dayRange" :key="'d' + day">
                    {{ day }}
                </option>
            </select>
        </div>

        <div class="segment">
            <p>Hours</p>
            <select v-model.number="hours" v-on:change="emitEvent">
                <option v-for="hour in hourRange" :key="'h' + hour">
                    {{ hour }}
                </option>
            </select>
        </div>

        <div class="segment">
            <p>Minutes</p>
            <select v-model.number="minutes" v-on:change="emitEvent">
                <option v-for="minute in minuteRange" :key="'m' + minute">
                    {{ minute }}
                </option>
            </select>
        </div>

        <div class="segment">
            <p>Seconds</p>
            <select v-model.number="seconds" v-on:change="emitEvent">
                <option v-for="second in secondRange" :key="'s' + second">
                    {{ second }}
                </option>
            </select>
        </div>
    </div>
</template>


<script>
const MINUTE = 60;
const HOUR = MINUTE * 60;
const DAY = HOUR * 24;
const WEEK = DAY * 7;

export default {
    props: {
        timestamp: {
            // In seconds
            default: 0,
            type: Number,
        },
    },
    data() {
        return {
            weekRange: [...Array(500).keys()],
            dayRange: [...Array(7).keys()],
            hourRange: [...Array(24).keys()],
            minuteRange: [...Array(60).keys()],
            secondRange: [...Array(60).keys()],
            weeks: undefined,
            days: undefined,
            hours: undefined,
            minutes: undefined,
            seconds: undefined,
        };
    },
    methods: {
        emitEvent() {
            const timestamp =
                this.seconds +
                this.minutes * MINUTE +
                this.hours * HOUR +
                this.days * DAY +
                this.weeks * WEEK;
            this.$emit("newTimestamp", timestamp);
        },
        setupValues(timestamp) {
            this.weeks = Math.floor(timestamp / WEEK)
            timestamp += -this.weeks * WEEK

            this.days = Math.floor(timestamp / DAY)
            timestamp += -this.days * DAY

            this.hours = Math.floor(timestamp / HOUR)
            timestamp += -this.hours * HOUR

            this.minutes = Math.floor(timestamp / MINUTE)
            timestamp += -this.minutes * MINUTE

            this.seconds = timestamp
        }
    },
    watch: {
        timestamp(timestamp) {
            this.setupValues(timestamp)
        },
    },
    mounted() {
        this.setupValues(this.timestamp)
    }
};
</script>


<style scoped>

div.timestamp_widget {
    display: flex;
    flex-direction: row;
}

div.segment {
    padding-right: 0.4rem;
}

p {
    text-transform: uppercase;
    font-size: 0.6rem;
    line-height: 1;
    margin: 0;
}
</style>
```
It's similar to that jQuery one. What do you think?

It looks like this:

<img width="256" alt="Screenshot 2021-01-02 at 21 13 57" src="https://user-images.githubusercontent.com/350976/103466746-81bf2c00-4d3f-11eb-9954-bab04788748c.png">

**Comment by sinisaos** [comment]
@dantownsend I think that looks awesome and that should be widget for Interval fields. It's much better than slider. Just add width:100% to div.segment

![edit](https://user-images.githubusercontent.com/30960668/103477198-7c53f700-4dbc-11eb-8032-670f36f546c6.png)

**Comment by dantownsend** [comment]
@sinisaos In the duration column in your screenshot, I think it would be cool if we changed that so it uses the format you used in your slider e.g. `5 minutes 3 seconds` instead of `303`.

**Comment by sinisaos** [comment]
@dantownsend Something like this

![create](https://user-images.githubusercontent.com/30960668/103508996-6bf65780-4e62-11eb-81c1-dd46a520799c.png)

On the small screen, the `Interval` widget is too wide. So I change the width of the sidebar of the `right_column` and I replaced the filter and sort buttons (withouth CSS order property like in above screenshot)

![mobile](https://user-images.githubusercontent.com/30960668/103509492-90066880-4e63-11eb-891e-e7ce35e55b66.png)

**Comment by dantownsend** [comment]
@sinisaos I've merged your work in now. I added a few commits to improve the buttons on mobile.

I'm really pleased with how the new widget and bulk deletion turned out, so thanks for your help 👍

**Comment by sinisaos** [comment]
@dantownsend Thanks. Glad I can help :). Its look really good.
