### ISSUE TITLE
Tweaks to release script

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#94]
If trying to release via GitHub there's currently a problem because the node dependencies aren't installed.

**Comment by dantownsend** [comment]
This is something which we really need to get fixed, as releasing new versions is done manually at the moment.

It means we don't have release notes on GitHub, which would be especially useful for Piccolo Admin, as we could include screenshots of new features.

**Comment by olliglorioso** [comment]
https://github.com/piccolo-orm/piccolo_admin/pull/186
Does this fix the problem, or did I understood something wrong?

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo_admin/pull/186
