### ISSUE TITLE
Form improvements

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#96]
I've been using form a lot, and there are a couple of things which could be improved.

`FormConfig` should accept coroutines as well as standard functions.

When there's an error, the banner shows up in green. I think we have the ability to show it in red.

**Comment by sinisaos** [comment]
@dantownsend Can you please close this issue because it's done.

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo_admin/issues/70
